<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Project_Minutes</RootNamespace>
    <AssemblyName>Project_Minutes.Domain</AssemblyName>
  </PropertyGroup>

</Project>
